name: Railway Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Railway CLI
        run: |
          curl -sSL https://get.railway.app | sh
          sudo mv /usr/local/bin/railway /usr/bin/railway
      - name: Login to Railway
        run: |
          railway login --token ${{ secrets.RAILWAY_TOKEN }}
      - name: Deploy to Railway
        run: railway link -n && railway deploy
